/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 11 21:32:59 GMT 2019
 */

package org.apache.commons.math4.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math4.exception.InsufficientDataException;
import org.apache.commons.math4.exception.util.Localizable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class InsufficientDataException_ESTest extends InsufficientDataException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Localizable localizable0 = mock(Localizable.class, new ViolatedAssumptionAnswer());
      Object[] objectArray0 = new Object[6];
      objectArray0[0] = (Object) objectArray0;
      InsufficientDataException insufficientDataException0 = null;
      try {
        insufficientDataException0 = new InsufficientDataException(localizable0, objectArray0);
        fail("Expecting exception: StackOverflowError");
      
      } catch(StackOverflowError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Object[] objectArray0 = new Object[0];
      InsufficientDataException insufficientDataException0 = new InsufficientDataException((Localizable) null, objectArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      InsufficientDataException insufficientDataException0 = new InsufficientDataException();
  }
}
