/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 11 21:41:56 GMT 2019
 */

package org.apache.commons.math4.dfp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math4.dfp.Dfp;
import org.apache.commons.math4.dfp.DfpField;
import org.apache.commons.math4.dfp.DfpMath;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DfpMath_ESTest extends DfpMath_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Dfp[] dfpArray0 = new Dfp[0];
      // Undeclared exception!
      try { 
        DfpMath.splitPow(dfpArray0, (-2953));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      // Undeclared exception!
      try { 
        DfpMath.splitMult((Dfp[]) null, (Dfp[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Dfp[] dfpArray0 = new Dfp[0];
      // Undeclared exception!
      try { 
        DfpMath.splitMult(dfpArray0, dfpArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      // Undeclared exception!
      try { 
        DfpMath.splitDiv((Dfp[]) null, (Dfp[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DfpField dfpField0 = mock(DfpField.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        DfpMath.split(dfpField0, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      // Undeclared exception!
      try { 
        DfpMath.sinInternal((Dfp[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Dfp[] dfpArray0 = new Dfp[1];
      // Undeclared exception!
      try { 
        DfpMath.sinInternal(dfpArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      // Undeclared exception!
      try { 
        DfpMath.sin((Dfp) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      // Undeclared exception!
      try { 
        DfpMath.pow((Dfp) null, (Dfp) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      // Undeclared exception!
      try { 
        DfpMath.pow((Dfp) null, (-1622));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Dfp[] dfpArray0 = new Dfp[0];
      // Undeclared exception!
      try { 
        DfpMath.logInternal(dfpArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      // Undeclared exception!
      try { 
        DfpMath.log((Dfp) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      // Undeclared exception!
      try { 
        DfpMath.expInternal((Dfp) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      // Undeclared exception!
      try { 
        DfpMath.exp((Dfp) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Dfp[] dfpArray0 = new Dfp[0];
      // Undeclared exception!
      try { 
        DfpMath.cosInternal(dfpArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      // Undeclared exception!
      try { 
        DfpMath.cos((Dfp) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      // Undeclared exception!
      try { 
        DfpMath.atanInternal((Dfp) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.dfp.Dfp", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      // Undeclared exception!
      try { 
        DfpMath.atan((Dfp) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      // Undeclared exception!
      try { 
        DfpMath.acos((Dfp) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      DfpField dfpField0 = mock(DfpField.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dfpField0).getRadixDigits();
      doReturn((Dfp) null, (Dfp) null).when(dfpField0).newDfp(anyString());
      Dfp[] dfpArray0 = DfpMath.split(dfpField0, "1.33333");
      assertEquals(2, dfpArray0.length);
      assertNotNull(dfpArray0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      DfpField dfpField0 = mock(DfpField.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dfpField0).getRadixDigits();
      doReturn((Dfp) null, (Dfp) null).when(dfpField0).newDfp(anyString());
      Dfp[] dfpArray0 = DfpMath.split(dfpField0, "YM6h9&kZ7");
      assertEquals(2, dfpArray0.length);
      assertNotNull(dfpArray0);
      
      // Undeclared exception!
      try { 
        DfpMath.logInternal(dfpArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      DfpField dfpField0 = mock(DfpField.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dfpField0).getRadixDigits();
      doReturn((Dfp) null, (Dfp) null).when(dfpField0).newDfp(anyString());
      Dfp[] dfpArray0 = DfpMath.split(dfpField0, "-0.25");
      // Undeclared exception!
      try { 
        DfpMath.cosInternal(dfpArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      DfpField dfpField0 = mock(DfpField.class, new ViolatedAssumptionAnswer());
      doReturn((Dfp) null, (Dfp) null).when(dfpField0).newDfp(anyString());
      Dfp[] dfpArray0 = DfpMath.split(dfpField0, "");
      // Undeclared exception!
      try { 
        DfpMath.splitPow(dfpArray0, 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      // Undeclared exception!
      try { 
        DfpMath.asin((Dfp) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      // Undeclared exception!
      try { 
        DfpMath.tan((Dfp) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      // Undeclared exception!
      try { 
        DfpMath.split((Dfp) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Dfp[] dfpArray0 = new Dfp[0];
      // Undeclared exception!
      try { 
        DfpMath.splitDiv(dfpArray0, dfpArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("org.apache.commons.math4.dfp.DfpMath", e);
      }
  }
}
